spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.Oracle8iDialect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: system
    password: manager
    driver-class-name: oracle.jdbc.driver.OracleDriver